<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="0.6.117" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetIdServer.Infrastructure\PetIdServer.Infrastructure.csproj"/>
  </ItemGroup>

</Project>
