<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
    <UserSecretsId>5744b9b5-0fcd-49b3-9933-2aec9245aeaa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SecretsManager" Version="3.7.400.97"/>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0"/>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.2"/>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetIdServer.Application\PetIdServer.Application.csproj"/>
    <ProjectReference Include="..\PetIdServer.Persistence\PetIdServer.Persistence.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
