// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetIdServer.Persistence;

#nullable disable

namespace PetIdServer.Persistence.Migrations
{
    [DbContext(typeof(PetIdContext))]
    [Migration("20250131100619_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pet")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetIdServer.Persistence.Entities.PetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCastrated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_castrated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.Property<bool>("Sex")
                        .HasColumnType("boolean")
                        .HasColumnName("sex");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("pets", "pet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.TagEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("code");

                    b.Property<long>("ControlCode")
                        .HasColumnType("bigint")
                        .HasColumnName("control_code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HashCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("hash_code");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scanned_at");

                    b.Property<DateTime?>("PetAddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pet_added_at");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.HasKey("Id");

                    b.HasIndex("PetId")
                        .IsUnique();

                    b.ToTable("tags", "pet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.TagReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CorruptedTagId")
                        .HasColumnType("integer")
                        .HasColumnName("corrupted_tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ReporterId")
                        .HasMaxLength(32)
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ResolverId")
                        .HasMaxLength(32)
                        .HasColumnType("uuid")
                        .HasColumnName("resolver_id");

                    b.Property<Guid?>("UserEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorruptedTagId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("ResolverId");

                    b.HasIndex("UserEntityId");

                    b.ToTable("tag_reports", "pet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.UserContactEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("ContactType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_type");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("contact");

                    b.HasKey("UserId", "ContactType");

                    b.ToTable("user_contacts", "pet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", "pet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.PetEntity", b =>
                {
                    b.HasOne("PetIdServer.Persistence.Entities.UserEntity", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.TagEntity", b =>
                {
                    b.HasOne("PetIdServer.Persistence.Entities.PetEntity", "PairedPet")
                        .WithOne("PairedTag")
                        .HasForeignKey("PetIdServer.Persistence.Entities.TagEntity", "PetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PairedPet");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.TagReportEntity", b =>
                {
                    b.HasOne("PetIdServer.Persistence.Entities.TagEntity", "CorruptedTag")
                        .WithMany("Reports")
                        .HasForeignKey("CorruptedTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetIdServer.Persistence.Entities.UserEntity", "Reporter")
                        .WithMany("TagReportsCreated")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PetIdServer.Persistence.Entities.UserEntity", "Resolver")
                        .WithMany("TagReportsResolved")
                        .HasForeignKey("ResolverId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PetIdServer.Persistence.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserEntityId");

                    b.Navigation("CorruptedTag");

                    b.Navigation("Reporter");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.UserContactEntity", b =>
                {
                    b.HasOne("PetIdServer.Persistence.Entities.UserEntity", "User")
                        .WithMany("Contacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.PetEntity", b =>
                {
                    b.Navigation("PairedTag")
                        .IsRequired();
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.TagEntity", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("PetIdServer.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Pets");

                    b.Navigation("TagReportsCreated");

                    b.Navigation("TagReportsResolved");
                });
#pragma warning restore 612, 618
        }
    }
}
